cmdb/urls.py
from django.conf.urls import url
from django.views.decorators.csrf import csrf_exempt
from cmdb.views.HostView import HostSearchView,HostAddView,HostUpdateView,HostDeleteView,HostAppUpdateInfoView,HostProjectModuelView,HostMidUpdateInfoView,HostMiddleWareView,HostDbUpdateInfoView
from cmdb.views.MiddlewareView import MiddlewareSearchView,MiddlewareAddView,MiddlewareUpdateView,MiddlewareDeleteView,MiddleWareInstall
# from cmdb.views.ProjectView import ProjectSearchView,ProjectAddView,ProjectUpdateView,ProjectDeleteView
# from cmdb.views.ProjectModuleView import ProjectModuleSearchView,ProjectModuleAddView,ProjectModuleUpdateView,ProjectModuleDeleteView,ProjectModuleDetailView,ProjectModuleConfigView,ProjectModuleUpdateInfo
from cmdb.views.ClusterView import ClusterSearchView,ClusterAddView,ClusterUpdateView,ClusterDeleteView,ClusterDetailView
from cmdb.views.IpPoolView import IpPoolSearchView,IpPoolAddView,IpPoolUpdateView,IpPoolDeleteView
from cmdb.views.DomainNameView import DomainNameSearchView,DomainNameAddView,DomainNameUpdateView,DomainNameDeleteView
from cmdb.views.DatabaseView import DatabaseSearchView,DatabaseAddView,DatabaseUpdateView,DatabaseDeleteView,DatabaseDetail
from cmdb.views.WebHook import WebHookTrigger
from cmdb.views.DbSchemaView import DbSchemaSearchView,DbSchemaAddView,DbSchemaUpdateView
from cmdb.views.RdsInstanceView import RdsInstanceSearchView,RdsInstanceAddView,RdsInstanceUpdateView,RdsInstanceDeleteView
from cmdb.views.RdsSchemaView import RdsSchemaSearchView,RdsSchemaAddView,RdsSchemaUpdateView,RdsSchemaDeleteView
from cmdb.views.EcsHostView import EcsHostSearchView,EcsHostAddView,EcsHostUpdateView,EcsHostDeleteView,EcsHostScanInfoView,EcsHostInitView,EcsHostInitResView,JenkinsAdd,ZabbixAdd

urlpatterns = [
    url(r"^host/$",csrf_exempt(HostSearchView.as_view()),name="host"),
    url(r"^host/add/$",csrf_exempt(HostAddView.as_view()),name="host_add"),
    url(r"^host/update/(?P<id>[0-9]+)/$",csrf_exempt(HostUpdateView.as_view()),name="host_update"),
    url(r"^host/delete/(?P<id>[0-9]+)/$",csrf_exempt(HostDeleteView.as_view()),name="host_delete"),
    url(r"^hostinfo/app/update/(?P<hostname>(.*))/$",HostAppUpdateInfoView.as_view(),name="host_app_info_update"),
    url(r"^hostinfo/mid/update/(?P<hostname>(.*))/$",HostMidUpdateInfoView.as_view(),name="host_mid_info_update"),
    url(r"^hostinfo/db/update/(?P<hostname>(.*))/$",HostDbUpdateInfoView.as_view(),name="host_db_info_update"),
    url(r"^host/projectmodule/info/(?P<id>[0-9]+)/$",HostProjectModuelView.as_view(),name="host_projetmodule_info"),
    url(r"^host/middleware/info/(?P<hostname>(.*))/$",HostMiddleWareView.as_view(),name="host_middleware_info"),
    url(r"^middleware/$",csrf_exempt(MiddlewareSearchView.as_view()),name="middleware"),
    url(r"^middleware/add/$",csrf_exempt(MiddlewareAddView.as_view()),name="middleware_add"),
    url(r"^middleware/update/(?P<id>[0-9]+)/$",csrf_exempt(MiddlewareUpdateView.as_view()),name="middleware_update"),
    url(r"^middleware/delete/(?P<id>[0-9]+)/$",csrf_exempt(MiddlewareDeleteView.as_view()),name="middleware_delete"),
    url(r"^middleware/install/(?P<midware>(.*))/$",MiddleWareInstall.as_view(),name="middleware_install"),
    url(r"^middleware/install/$",csrf_exempt(MiddleWareInstall.as_view()),name="mid_install"),
    # url(r"^project/$",csrf_exempt(ProjectSearchView.as_view()),name="project"),
    # url(r"^project/add/$",csrf_exempt(ProjectAddView.as_view()),name="project_add"),
    # url(r"^project/update/(?P<id>[0-9]+)/$",csrf_exempt(ProjectUpdateView.as_view()),name="project_update"),
    # url(r"^project/delete/(?P<id>[0-9]+)/$",csrf_exempt(ProjectDeleteView.as_view()),name="project_delete"),
    # url(r"^projectmodule/detail/(?P<name>(.*))/$",ProjectModuleDetailView.as_view(),name="project_detail"),
    # url(r"^projectmodule/$",csrf_exempt(ProjectModuleSearchView.as_view()),name="projectmodule"),
    # url(r"^projectmodule/add/$",csrf_exempt(ProjectModuleAddView.as_view()),name="projectmodule_add"),
    # url(r"^projectmodule/update/(?P<id>[0-9]+)/$",csrf_exempt(ProjectModuleUpdateView.as_view()),name="projectmodule_update"),
    # url(r"^projectmodule/delete/(?P<id>[0-9]+)/$",csrf_exempt(ProjectModuleDeleteView.as_view()),name="projectmodule_delete"),
    # url(r"^projectmodule/config/(?P<id>[0-9]+)/$",ProjectModuleConfigView.as_view(),name="projectmodule_config"),
    # url(r"^projectmodule/updateinfo/(?P<module_name>(.*))/$",ProjectModuleUpdateInfo.as_view(),name="projectmodule_update_info"),
    url(r"^cluster/$",csrf_exempt(ClusterSearchView.as_view()),name="cluster"),
    url(r"^cluster/add/$",csrf_exempt(ClusterAddView.as_view()),name="cluster_add"),
    url(r"^cluster/update/(?P<id>[0-9]+)/$",csrf_exempt(ClusterUpdateView.as_view()),name="cluster_update"),
    url(r"^cluster/delete/(?P<id>[0-9]+)/$",csrf_exempt(ClusterDeleteView.as_view()),name="cluster_delete"),
    url(r"^cluster/hostinfo/(?P<cluster_name>(.*))/$",ClusterDetailView.as_view(),name="cluster_host_info"),
    url(r"^ippool/$",csrf_exempt(IpPoolSearchView.as_view()),name="ippool"),
    url(r"^ippool/add/$",csrf_exempt(IpPoolAddView.as_view()),name="ippool_add"),
    url(r"^ippool/update/(?P<id>[0-9]+)/$",csrf_exempt(IpPoolUpdateView.as_view()),name="ippool_update"),
    url(r"^ippool/delete/(?P<id>[0-9]+)/$",csrf_exempt(IpPoolDeleteView.as_view()),name="ippool_delete"),
    url(r"^domainname/$",csrf_exempt(DomainNameSearchView.as_view()),name="domainname"),
    url(r"^domainname/add/$",csrf_exempt(DomainNameAddView.as_view()),name="domainname_add"),
    url(r"^domainname/update/(?P<id>[0-9]+)/$",csrf_exempt(DomainNameUpdateView.as_view()),name="domainname_update"),
    url(r"^domainname/delete/(?P<id>[0-9]+)/$",csrf_exempt(DomainNameDeleteView.as_view()),name="domainname_delete"),
    url(r"^database/$",csrf_exempt(DatabaseSearchView.as_view()),name="database"),
    url(r"^database/add/$",csrf_exempt(DatabaseAddView.as_view()),name="database_add"),
    url(r"^database/update/(?P<id>[0-9]+)/$",csrf_exempt(DatabaseUpdateView.as_view()),name="database_update"),
    url(r"^database/delete/(?P<id>[0-9]+)/$",csrf_exempt(DatabaseDeleteView.as_view()),name="database_delete"),
    url(r"^database/detail/(?P<instance>(.*))/$",DatabaseDetail.as_view(),name="database_detail"),
    url(r"^dbschema/$",csrf_exempt(DbSchemaSearchView.as_view()),name="dbschema"),
    url(r"^dbschema/add/$",csrf_exempt(DbSchemaAddView.as_view()),name="dbschema_add"),
    url(r"^dbschema/update/(?P<id>[0-9]+)/$",csrf_exempt(DbSchemaUpdateView.as_view()),name="dbschema_update"),
    url(r"^webhook/info/$",csrf_exempt(WebHookTrigger.as_view()),name="webhook_info"),
    url(r"rdsinstance/list/$",csrf_exempt(RdsInstanceSearchView.as_view()),name="rdsinstance_list"),
    url(r"rdsinstance/add/$",csrf_exempt(RdsInstanceAddView.as_view()),name="rdsinstance_add"),
    url(r"rdsinstance/update/(?P<id>[0-9]+)/$",csrf_exempt(RdsInstanceUpdateView.as_view()),name="rdsinstance_update"),
    url(r"rdsinstance/delete/(?P<id>[0-9]+)/$",csrf_exempt(RdsInstanceDeleteView.as_view()),name="rdsinstance_delete"),
    url(r"^rdsschema/list/$",csrf_exempt(RdsSchemaSearchView.as_view()),name="rdsschema_list"),
    url(r"^rdsschema/add/$",csrf_exempt(RdsSchemaAddView.as_view()),name="rdsschema_add"),
    url(r"^rdsschema/update/(?P<id>[0-9]+)/$",csrf_exempt(RdsSchemaUpdateView.as_view()),name="rdsschema_update"),
    url(r"^rdsschema/delete/(?P<id>[0-9]+)/$",csrf_exempt(RdsSchemaDeleteView.as_view()),name="rdsschema_delete"),
    url(r"^ecshost/list/$",csrf_exempt(EcsHostSearchView.as_view()),name="ecshost_list"),
    url(r"^ecshost/add/$",csrf_exempt(EcsHostAddView.as_view()),name="ecshost_add"),
    url(r"^ecshost/update/(?P<id>[0-9]+)/$",csrf_exempt(EcsHostUpdateView.as_view()),name="ecshost_update"),
    url(r"^ecshost/delete/(?P<id>[0-9]+)/$",csrf_exempt(EcsHostDeleteView.as_view()),name="ecshost_delete"),
    url(r"^ecshost/scan/info/(?P<minion_id>(.*))/$",csrf_exempt(EcsHostScanInfoView.as_view()),name="ecshost_scan_info"),
    url(r"^ecshost/init/(?P<id>[0-9]+)/$",csrf_exempt(EcsHostInitView.as_view()),name="ecs_init"),
    url(r"^ecshost/install/$",csrf_exempt(EcsHostInitView.as_view()),name="ecs_install"),
    url(r"^ecshost/install/res/(?P<target>(.*))/$",csrf_exempt(EcsHostInitResView.as_view()),name="ecs_install_res"),
    url(r"^echost/jenkins/add/(?P<id>[0-9]+)/$",csrf_exempt(JenkinsAdd.as_view()),name="ecs_jenkins_add"),
    url(r"^ecshos/zabbix/add/(?P<id>[0-9]+)/$",csrf_exempt(ZabbixAdd.as_view()),name="ecs_zabbix_add")
]

devops/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from common import views
from rest_framework_jwt.views import obtain_jwt_token
from django.conf.urls import handler403
from common.views import permission_denied

handler403 = permission_denied

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^common/',include('common.urls')),
    url(r'^cmdb/',include('cmdb.urls')),
    url(r'^project/',include('cmdb.urls_proj')),
    url(r'^accounts/login/$',views.LoginView.as_view(),name="login"),
    url(r'^dxwf/',include('dxwf.urls')),
    url(r'^api/',include('cmdbapi.urls')),
    url(r'^api-auth/',obtain_jwt_token),
    url(r'^import/',include('import_data.urls')),
    url(r'^jenkinsapi/',include('jenkinsapi.urls')),
    url(r'^deploy/',include('deploy.urls')),
    url(r'^account/',include('account.urls')),
    url(r'^ldap/',include('ldapmanage.urls'))
]

cmdb/models/ProjectModule.py
from django.db import models
from cmdb.models.Project import Project
from cmdb.models.Cluster import Cluster
from cmdb.models.DbSchema import DbSchema

class ProjectModule(models.Model):
    module_name = models.CharField(max_length=255,null=False,blank=False,verbose_name="模块名称",unique=True)
    module_desc = models.CharField(max_length=255,null=False,blank=False,verbose_name="模块描述")
    service_type = models.CharField(max_length=255,null=False,blank=False,verbose_name="服务")
    git_url = models.CharField(max_length=255,null=False,blank=False,verbose_name="git地址")
    project = models.ForeignKey(Project,null=False,blank=False,verbose_name="项目")
    db_schema = models.ForeignKey(DbSchema,null=True,blank=True,verbose_name="数据库")
    cluster = models.ManyToManyField(Cluster,null=True,blank=True,verbose_name="集群")

    def __str__(self):
        return self.module_name
    class Meta:
        verbose_name = "项目模块"
        verbose_name_plural = verbose_name
        permissions = (
            ("scan_projectmodule","Can scan projectmodule info"),
        )

cmdb/forms/ClusterForm.py
from django import forms
from django.forms import TextInput,Select,Textarea
from cmdb.forms.HostForm import env_type

cluster_type = (
    ("","请选择"),
    ("app","应用系统集群"),
    ("db","数据库集群"),
    ("middleware","中间件集群")
)

class ClusterSearchForm(forms.Form):
    search_cluster_name = forms.CharField(
        widget = TextInput(attrs={"id":"search_cluster_name","class":"form-control","placeholder":"请输入集群名称"}),
        required=False
    )
    search_cluster_type = forms.CharField(
        widget = Select(attrs={"id":"search_cluster_type","class":"form-control"},choices=cluster_type)
    )

class ClusterAddForm(forms.Form):
    cluster_name = forms.CharField(
        widget = TextInput(attrs={"id":"cluster_name","class":"form-control","placeholder":"请输入集群名称"})
    )
    cluster_type = forms.CharField(
        widget = Select(attrs={"id":"cluster_type","class":"form-control"},choices=cluster_type)
    )
    cluster_desc = forms.CharField(
        widget = Textarea(attrs={"id":"cluster_desc","class":"form-control"}),
        required=False
    )
    environment = forms.CharField(
        widget = Select(attrs={"id":"environment","class":"form-control"},choices=env_type)
    )

cmdb/forms/DatabaseForm.py
from django import forms
from django.forms import TextInput,Select
from cmdb.models.Cluster import Cluster
from cmdb.models.Host import Host

db_type = (
    ("","请选择"),
    ("mysql","MySQL"),
    ("oracle","Oracle"),
    ("postgresql","Postgresql")
)
class DatabaseSearchForm(forms.Form):
    search_schema = forms.CharField(
        widget = TextInput(attrs={"id":"search_schema","class":"form-control","placeholder":"请输入实例名称"}),
        required=False
    )
    search_db_type = forms.CharField(
        widget = Select(attrs={"id":"search_db_type","class":"form-control"},choices=db_type)
    )

class DatabaseAddForm(forms.Form):
    instance = forms.CharField(
        widget = TextInput(attrs={"id":"instance","class":"form-control","placeholder":"请输入实例名称"})
    )
    db_type = forms.CharField(
        widget = Select(attrs={"id":"db_type","class":"form-control"},choices=db_type)
    )
    cluster = forms.CharField(
        widget = Select(attrs={"id":"cluster","class":"form-control"}),required=False
    )
    host = forms.CharField(
        widget = Select(attrs={"id":"host","class":"form-control"}),
        required=False
    )
    def __init__(self,*args,**kwargs):
        super(DatabaseAddForm,self).__init__(*args,**kwargs)
        cluster_choices = list(Cluster.objects.all().values_list("id","cluster_name"))
        cluster_choices.insert(0,("","请选择"))
        host_choices = list(Host.objects.all().values_list("id","host_name"))
        host_choices.insert(0,("","请选择"))
        self.fields["cluster"].widget.choices = cluster_choices
        self.fields["host"].widget.choices = host_choices

cmdb/forms/DbSchemaForm.py
from django import forms
from django.forms import TextInput,Textarea,Select
from cmdb.models.Database import Database

class DbSchemaSearchForm(forms.Form):
    search_schema = forms.CharField(
        widget = TextInput(attrs={"id":"search_schema","class":"form-control","placeholder":"请输入database名称"}),
        required=False
    )
    search_instance = forms.CharField(
        widget = Select(attrs={"id":"search_instance","class":"form-control"})
    )
    def __init__(self,*args,**kwargs):
        super(DbSchemaSearchForm,self).__init__(*args,**kwargs)
        instance_choice = list(Database.objects.all().values_list("id","instance"))
        instance_choice.insert(0,("","请选择"))
        self.fields["search_instance"].widget.choices = instance_choice

class DbSchemaAddForm(forms.Form):
    schema = forms.CharField(
        widget = TextInput(attrs={"id":"schema","class":"form-control","placeholder":"请输入database名称"})
    )
    url = forms.CharField(
        widget = TextInput(attrs={"id":"url","class":"form-control","placeholder":"请输入连接地址"})
    )
    port = forms.CharField(
        widget = TextInput(attrs={"id":"port","class":"form-control","placeholder":"请输入端口"})
    )
    user = forms.CharField(
        widget = TextInput(attrs={"id":"user","class":"form-control","placeholder":"请输入用户名"}),
        required=False
    )
    password = forms.CharField(
        widget = TextInput(attrs={"id":"password","class":"form-control","placeholder":"请输入密码"}),
        required=False
    )
    instance = forms.CharField(
        widget = Select(attrs={"id":"instance","class":"form-control"})
    )
    def __init__(self,*args,**kwargs):
        super(DbSchemaAddForm,self).__init__(*args,**kwargs)
        instance_choice = list(Database.objects.all().values_list("id","instance"))
        instance_choice.insert(0,("","请选择"))
        self.fields["instance"].widget.choices = instance_choice

cmdb/forms/DomainNameForm.py
from django import forms
from django.forms import TextInput,Select
from cmdb.forms.HostForm import env_type
from cmdb.models.ProjectModule import ProjectModule
from cmdb.models.IpPool import IpPool

domainname_type = (
    ("","请选择"),
    ("A","A"),
    ("CNAME","CNAME")
)


class DomainNameSearchForm(forms.Form):
    search_dns = forms.CharField(
        widget = TextInput(attrs={"id":"search_dns","class":"form-control","placeholder":"请输入dns域名"}),
        required=False
    )
    search_ip_address = forms.CharField(
        widget = Select(attrs={"id":"search_ip_address","class":"select2 form-control"},choices=env_type)
    )
    def __init__(self,*args,**kwargs):
        super(DomainNameSearchForm,self).__init__(*args,**kwargs)
        ip_choice = list(IpPool.objects.all().values_list("id","ip_address"))
        ip_choice.insert(0,("","请选择"))
        self.fields["search_ip_address"].widget.choices = ip_choice


class DomainNameAddForm(forms.Form):
    dns = forms.CharField(
        widget = TextInput(attrs={"id":"dns","class":"form-control","placeholder":"请输入dns域名"}),
    )
    domain_type = forms.CharField(
        widget = Select(attrs={"id":"domain_type","class":"form-control"},choices = domainname_type)
    )
    ip = forms.CharField(
        widget = Select(attrs={"id":"ip","class":"form-control select2"})
    )
    project_module = forms.CharField(
        widget = Select(attrs={"id":"project_module","class":"form-control"}),
        required=False
    )
    project_module_url = forms.CharField(
        widget = TextInput(attrs={"id":"project_module_url","class":"form-control","placeholder":"请输入项目模块访问地址"}),
        required=False
    )
    environment = forms.CharField(
        widget = Select(attrs={"id":"environment","class":"form-control"},choices=env_type),
        required=False
    )

    def __init__(self,*args,**kwargs):
        super(DomainNameAddForm,self).__init__(*args,**kwargs)
        projectmodule_choice = list(ProjectModule.objects.all().values_list("id","module_name"))
        projectmodule_choice.insert(0,("","请选择"))
        self.fields["project_module"].widget.choices = projectmodule_choice
        ip_choices = list(IpPool.objects.all().values_list("id","ip_address"))
        ip_choices.insert(0,("","请选择"))
        self.fields["ip"].widget.choices = ip_choices

templates/cmdb/projectmodule/projectmodule_add.html
{% extends "common/form_base.html" %}
{% block content_title %}
    编辑项目模块
    <small>新增项目模块</small>
{% endblock %}
{% block child_uri %}
    <li><a href="{% url 'projectmodule' %}">模块管理</a></li>
    <li><a href="" class="active">新增项目模块</a></li>
{% endblock %}
{% block add_form %}
    <style>
    .select2-container--default .select2-selection--single {
        height:34px;
        background-color: #fff;
        border: 1px solid #aaa;
        border-radius: 0px;
    }
    </style>
    <form action="" method="post" class="form-horizontal">
        <div class="box-body">
            <div class="form-group">
                <div class="col-xs-6">
                    <label for="pro_name"> 模块名称</label>
                    {{ projectmodule_add_form.module_name }}
                    {% ifequal repeat_errors "true"  %}
                        <span>模块已经存在</span>
                    {% endifequal %}
                </div>
            </div>
            <div class="form-group">
                <div class="col-xs-6">
                    <label for="department_name">模块描述</label>
                    {{ projectmodule_add_form.module_desc }}
                </div>
            </div>
            <div class="form-group">
                <div class="col-xs-6">
                    <label for="stage_name">模块服务类型</label>
                    {{ projectmodule_add_form.service_type }}
                </div>
            </div>
            <div class="form-group">
                <div class="col-xs-6">
                    <label for="charge_name">git代码链接地址</label>
                    {{ projectmodule_add_form.git_url }}
                </div>
            </div>
            <div class="form-group">
                <div class="col-xs-6">
                    <label for="describe_text">所属项目</label>
                    {{ projectmodule_add_form.project }}
                </div>
            </div>
{#            <div class="form-group">#}
{#                <div class="col-xs-6">#}
{#                    <label for="describe_text">集群</label>#}
{#                    {{ projectmodule_add_form.cluster }}#}
{#                </div>#}
{#            </div>#}
        </div>
        <!-- /.box-body -->
        <div class="box-footer">
            <button class="btn btn-default"><a href="{% url 'projectmodule' %}">取消</a></button>
            <button class="btn btn-info" id="addtrue" type="submit">确定</button>
        </div>
    </form>
{% endblock %}

templates/cmdb/projectmodule/projectmodule_detail.html
{% extends "common/base.html" %}
{% load pagination_tags %}
{% block content_title %}
    模块列表
    <small>模块列表</small>
{% endblock %}
{% block uri %}
    <li><a href="#"><i class="fa fa-dashboard"></i> 控制台</a></li>
    <li class="active"><a href="#">模块管理</a></li>
    <li><a href="#">模块搜索条目</a></li>
{% endblock %}
{% block main_body %}
    <section class="content">
      <div class="row">
        <div class="col-xs-12">
          <div class="box">
            <div class="box-header">
            <form action="" method="post">
              <div class="col-xs-3 no-padding">
                <div class="input-group">
                  <div class="input-group-addon">
                    <i class="fa fa-search"></i>
                  </div>
                    {{ projectmodule_search_form.search_module_name }}
                </div>
              <span id="host_tip" style="position: absolute;left: 0;top: 40px;color: #ff5959;font-size: 12px;display: none">{% block warning %}{% endblock %}</span>
              </div>
              <div class="col-xs-2">
                  {{ projectmodule_search_form.search_proj_name }}
              </div>
              <div class="col-xs-3 no-padding">
                  <button class="btn btn-info flat" id="search_wf"><i class="fa fa-search"> </i> 搜索</button>
                  <button class="btn btn-info flat" data-toggle="modal" data-target="#edit_project"><a href="{% url 'projectmodule_add' %}" style="color: #fff;"><i class="fa fa-plus"> </i>新增模块</a></button>
              </div>
            </form>
            </div>
            <div class="box-body">
              <table class="table1 table text-center flat" id="hosttable">
                <thead>
                  <tr>
                        <th>模块名称</th>
                        <th>模块描述</th>
                        <th>项目</th>
                    <th>
                      <div>操作</div>
                    </th>
                  </tr>
                </thead>
                <tbody>
                    {% autopaginate projectmodule 10 %}
                    {% for pm in projectmodule %}
                    <tr>
                        <td>{{ pm.module_name }}</td>
                        <td>{{ pm.module_desc }}</td>
                        <td>{{ pm.project.name }}</td>
                        <td>
{#                            <a href="/project/projectmodule/updateinfo/{{ pm.module_name }}/">#}
{#                                <button class="btn btn-success btn-sm">更 新</button>#}
{#                            </a>#}
                            <a href="">
                                <button class="btn btn-success btn-sm">模 块</button>
                            </a>
                            <a href="/project/projectmodule/update/{{ pm.id }}/">
                                <button class="btn btn-warning btn-sm edit_btn" data-toggle="modal" data-target="#edit_project">修 改</button>
                            </a>
                            {% if perms.cmdb.delete_projectmodule %}
                            <a href="/project/projectmodule/delete/{{ pm.id }}/">
                                <button class="btn btn-danger btn-sm del_btn" data-toggle="modal" data-target="#del_project">删 除</button>
                            </a>
                            {% endif %}
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
              </table>
                {% paginate %}
            </div>
          </div>
        </div>
      </div>
    </section>
{% endblock %}

templates/cmdb/projectmodule/projectmodule_list.html
{% extends "common/base.html" %}
{% load pagination_tags %}
{% block content_title %}
    模块列表
    <small>模块列表</small>
{% endblock %}
{% block uri %}
    <li><a href="#"><i class="fa fa-dashboard"></i> 控制台</a></li>
    <li class="active"><a href="#">模块管理</a></li>
{% endblock %}
{% block main_body %}
    <section class="content">
      <div class="row">
        <div class="col-xs-12">
          <div class="box">
            <div class="box-header">
            <form action="" method="post">
              <div class="col-xs-3 no-padding">
                <div class="input-group">
                  <div class="input-group-addon">
                    <i class="fa fa-search"></i>
                  </div>
                    {{ projectmodule_search_form.search_module_name }}
                </div>
              <span id="host_tip" style="position: absolute;left: 0;top: 40px;color: #ff5959;font-size: 12px;display: none">{% block warning %}{% endblock %}</span>
              </div>
              <div class="col-xs-2">
                  {{ projectmodule_search_form.search_proj_name }}
              </div>
              <div class="col-xs-3 no-padding">
                  <button class="btn btn-info flat" id="search_wf"><i class="fa fa-search"> </i> 搜索</button>
                  <button class="btn btn-info flat" data-toggle="modal" data-target="#edit_project"><a href="{% url 'projectmodule_add' %}" style="color: #fff;"><i class="fa fa-plus"> </i>新增模块</a></button>
              </div>
            </form>
            </div>
            <div class="box-body">
              <table class="table1 table text-center flat" id="hosttable">
                <thead>
                  <tr>
                        <th>模块名称</th>
                        <th>模块描述</th>
                        <th>项目</th>
                    <th>
                      <div>操作</div>
                    </th>
                  </tr>
                </thead>
                <tbody>
                    {% autopaginate projectmodule 10 %}
                    {% for pm in projectmodule %}
                    <tr>
                        <td>{{ pm.module_name }}</td>
                        <td>{{ pm.module_desc }}</td>
                        <td>{{ pm.project.name }}</td>
                        <td>
{#                            <a href="/project/projectmodule/updateinfo/{{ pm.module_name }}/">#}
{#                                <button class="btn btn-success btn-sm">更 新</button>#}
{#                            </a>#}
                            <a href="">
                                <button class="btn btn-success btn-sm">模 块</button>
                            </a>
                            <a href="/project/projectmodule/update/{{ pm.id }}/">
                                <button class="btn btn-warning btn-sm edit_btn" data-toggle="modal" data-target="#edit_project">修 改</button>
                            </a>
                            {% if perms.cmdb.delete_projectmodule %}
                            <a href="/project/projectmodule/delete/{{ pm.id }}/">
                                <button class="btn btn-danger btn-sm del_btn" data-toggle="modal" data-target="#del_project">删 除</button>
                            </a>
                            {% endif %}
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
              </table>
                {% paginate %}
            </div>
          </div>
        </div>
      </div>
    </section>
{% endblock %}